onos-config:
  plugins:
    - name: testdevice
      version: 1.0.0
      image:
        repository: smbaker/config-model-testdevice-1.0.0
        tag: smbaker
    - name: testdevice
      version: 2.0.0
      image:
        repository: smbaker/config-model-testdevice-2.0.0
        tag: smbaker
    - name: aether
      version: 1.0.0
      image:
        repository: smbaker/config-model-aether-1.0.0
        tag: smbaker
    - name: aether
      version: 2.0.0
      image:
        repository: smbaker/config-model-aether-2.0.0
        tag: smbaker        
    - name: rbac
      version: 1.0.0
      image:
        repository: smbaker/config-model-rbac-1.0.0
        tag: smbaker
  image:
    repository: smbaker/onos-config
    tag: smbaker

onos-topo:
  image:
    repository: smbaker/onos-topo
    tag: smbaker
#    pullPolicy: Always

onos-sdran-cli:
  image:
    repository: onosproject/onos-sdran-cli
    tag: v0.7.0

#global:
#  storage:
#    controller: "atomix-controller.micro-onos.svc.cluster.local:5679"

import:
  sdcore-adapter:
    enabled: false

sdcore-adapter:
  # output: "/tmp/sdcore-adapter.out"
  # spgwEndpoint: "http://spgwc.omec:8080/v1/config"

onos-gui:
  ingress:
    enabled: false
  service:
    type: NodePort

aether-roc-gui:
  ingress:
    enabled: false
  service:
    type: NodePort

aether-roc-api:
   corsOrigins:
   - https://editor.swagger.io
