global:
  storage:
    controller: "atomix-controller.micro-onos.svc.cluster.local:5679"

import:
  sdcore-adapter:
    enabled: true

sdcore-adapter:
  output: "/tmp/sdcore-adapter.out"
  # spgwEndpoint: "http://spgwc.omec:8080/v1/config"

onos-gui:
  ingress:
    enabled: false
  service:
    type: NodePort

aether-roc-gui:
  ingress:
    enabled: false
  service:
    type: NodePort

aether-roc-api:
   corsOrigins:
   - https://editor.swagger.io
